language: php

install: composer install

matrix:
  include:
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: bionic
   # Default PHP version in macOS HighSierra(10.13.6) and Mojave(10.14.4)
    - php: 7.1.23
      dist: xenial
    - php: 7.2
      dist: bionic
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic
    - php: nightly
      dist: bionic

script: composer bench-summary && composer bench-memory && composer bench-time

jobs:
  allow_failures:
    - php: 5.6
    - php: 7.0
    - php: nightly
